//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LtkK22Cnt4Lesson10Cb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LtkAccount
    {
        public int LtkID { get; set; }
        public string LtkUserName { get; set; }
        public string LtkPassword { get; set; }
        public string LtkFullName { get; set; }
        public string LtkEmail { get; set; }
        public string LtkPhone { get; set; }
        public Nullable<bool> LtkActive { get; set; }
    }
}
