//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LtkK22CNT4Lesson07DF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ltkKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ltkKhoa()
        {
            this.ltkSinhVien = new HashSet<ltkSinhVien>();
        }
    [DisplayName("Ma Khoa")]
        public string ltkMaKH { get; set; }
        [DisplayName("Tên Khoa")]
        public string ltkTenKhoa { get; set; }
        [DisplayName("Trạng thái")]
        public Nullable<bool> ltkTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ltkSinhVien> ltkSinhVien { get; set; }
    }
}
