//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LtkK22CNT4Lesson07DF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LtkK22CNT4Lesson7DBEntities1 : DbContext
    {
        public LtkK22CNT4Lesson7DBEntities1()
            : base("name=LtkK22CNT4Lesson7DBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ltkKhoa> ltkKhoa { get; set; }
        public virtual DbSet<ltkSinhVien> ltkSinhVien { get; set; }
    }
}
