//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LtkK22CNT4Lesson07DF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ltkSinhVien
    {
        [DisplayName("Mã Sinh Viên")]
        public string ltkMaSV { get; set; }
        [DisplayName("Họ Sinh Viên")]
        public string LtkHoSV { get; set; }
        [DisplayName("Tên Sinh Viên")]
        public string LtkTenSV { get; set; }
        [DisplayName("Phái Sinh Viên")]
        public Nullable<bool> LtkPhai { get; set; }
        [DisplayName("Email Sinh Viên")]
        public string LtkEmail { get; set; }
        [DisplayName("SDT Sinh Viên")]
        public string LtkPhone { get; set; }
        [DisplayName("Mã Khoa")]
        public string LtkMaKH { get; set; }
        [DisplayName("Trạng thái")]
        public Nullable<bool> LtkTrangThai { get; set; }
    
        public virtual ltkKhoa ltkKhoa { get; set; }
    }
}
