//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeTrungKien_2210900034.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ltk_TacGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ltk_TacGia()
        {
            this.Ltk_Sach = new HashSet<Ltk_Sach>();
        }
    
        public string Ltk_MaTG { get; set; }
        public string Ltk_TenTG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ltk_Sach> Ltk_Sach { get; set; }
    }
}
