//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeTrungKien_2210900034.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LeTrungKien_2210900034Entities : DbContext
    {
        public LeTrungKien_2210900034Entities()
            : base("name=LeTrungKien_2210900034Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ltk_Sach> Ltk_Sach { get; set; }
        public virtual DbSet<Ltk_TacGia> Ltk_TacGia { get; set; }
    }
}
