//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LtkK22Cnt4Lesson11Cb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LtkCatagory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LtkCatagory()
        {
            this.LtkProduct = new HashSet<LtkProduct>();
        }
    [Display(Name ="Mã loại")]
        public int LtkID { get; set; }
        [Display(Name = "Tên danh mục")]
        public string LtkCateName { get; set; }
        [Display(Name = "Trạng thái")]
        public Nullable<bool> LtkStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LtkProduct> LtkProduct { get; set; }
    }
}
