//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LtkK22Cnt4Lesson11Cb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LtkProduct
    {
        public string LtkID2210900034 { get; set; }
        public string LtkProName { get; set; }
        public Nullable<int> LtkQty { get; set; }
        public Nullable<double> LtkPrice { get; set; }
        public Nullable<int> LtkCateId { get; set; }
        public Nullable<bool> LtkActive { get; set; }
    
        public virtual LtkCatagory LtkCatagory { get; set; }
    }
}
